apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: the-test-app
  description: Testing
  annotations:
    github.com/project-slug: ZensarIDP/the-test-app
    github.com/workflows: ci.yml
    backstage.io/environments: 'dev,staging,prod'
  tags:
    - nodejs
    - microservice
    - cloud-run
    - multi-environment
spec:
  type: service
  lifecycle: experimental
  owner: group:default/developers
  system: the-test-app-system
